name: QE Testing on Openshift

on:
  workflow_dispatch:
env:
  QE_REPO: test-network-function/cnfcert-tests-verification



jobs:
  qe-testing:
    runs-on: osgh1
    strategy:
      fail-fast: false
      matrix: 
        suite: [accesscontrol, affiliatedcertification, lifecycle, networking, observability, platformalteration, performance, operator]
    env:
      SHELL: /bin/bash
      DEBUG_TNF: true # More verbose output from the TNF
      KUBECONFIG: '/home/tnf/.kube/config'
      PFLT_DOCKERCONFIG: '/home/tnf/.docker/config'
      TEST_TNF_IMAGE_NAME: quay.io/testnetworkfunction/cnf-certification-test
      TEST_TNF_IMAGE_TAG: localtest
      DOCKER_CONFIG_DIR: '/home/tnf/.docker'

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      - name: Run initial setup
        uses: ./.github/actions/setup

      - name: Build the test image
        run: make build-image-local-podman # quay.io/testnetworkfunction/cnf-certification-test:localtest
        
      - name: Check out `cnf-certification-test-partner`
        uses: actions/checkout@v3
        with:
          repository: test-network-function/cnf-certification-test-partner
          path: cnf-certification-test-partner
            
      - name: Install partner resources
        run: make install
        working-directory: cnf-certification-test-partner

      - name: Clone the QE repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.QE_REPO }}
          path: cnfcert-tests-verification

      # Setup is complete.  Time to run the QE tests.
      - name: Run the tests
        run: FEATURES=${{matrix.suite}} TNF_REPO_PATH=${GITHUB_WORKSPACE} TNF_IMAGE=${{env.TEST_TNF_IMAGE_NAME}} TNF_IMAGE_TAG=${{env.TEST_TNF_IMAGE_TAG}} make test-features
        working-directory: cnfcert-tests-verification
